server:
  port: 9090
  servlet:
    session:
      persistent: false
      timeout: 0

spring:
  application:
    name: tecobraryapiv2
  profiles:
    active: local
---
spring:
  profiles: local
  cloud:
    config:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://mysql-db:3306/tecobrary?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: tecobrary
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profiles: dev
  cloud:
    config:
      uri: http://54.180.159.21:9999