version: "3"
services:
  api-server:
    image: tecobrary/tecobrary-api-server
    container_name: api-server
    restart: always
    depends_on:
      - "mysql-db"
    links:
      - mysql-db
    ports:
      - 9090:9090
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - 6033:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tecobrary
      MYSQL_PASSWORD: tecobrary
      MYSQL_DATABASE: tecobrary
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      - ./cnf/my.cnf:/etc/mysql/my.cnf
